Fixed bug 4615 - RPM Build fails due to unpackaged files
devbeer

The current SDL2.spec fails to build with:

Checking for unpackaged file(s): /usr/lib/rpm/check-files /tmp/build/rpmbuild/BUILDROOT/SDL2-2.0.9-2.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/lib64/cmake/SDL2/sdl2-config.cmake


RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib64/cmake/SDL2/sdl2-config.cmake